### ISSUE TITLE
aarch64-darwin is newly unsupported

### ISSUE THREAD

**Issue by BrianHicks** [nix-community/comma#17]
hey folks! I've been using comma for a while and it just stopped working on my aarch64-darwin machine. It was working as of 54149dc417819af14ddc0d59216d4add5280ad14, so I guess some change newer than that intentionally broke it (I see `x86_64-darwin` only now.)

Is there any way you could restore support for M1 Macs?

**Comment by Artturin** [comment]
fixed

**Comment by BrianHicks** [comment]
in 67f26046? No, it's still broken because of this line: https://github.com/nix-community/comma/blob/master/default.nix#L35

**Comment by BrianHicks** [comment]
@Artturin  would you mind reopening this? It is not yet solved.

**Comment by SuperSandro2000** [comment]
I think it would be a good idea to disable the prebuild DB if it isn't available instead of failing.
